My Project: src/tools.c File Reference
tools.c File Reference
Implementación de funciones de herramientas y utilidades.
#include "tools.h"
#include "main.h"
Functions
void launchProg (char **args, int background)
launchProg punto 3 de tp2 Ejecuta un programa externo con los argumentos dados args[]: Array de cadenas que representa el comando y sus argumentos. background: Indica si el proceso debe ejecutarse en segundo plano. Funcionamiento: Crea un proceso hijo usando fork(). Si background es 1, el proceso se ejecuta en segundo plano. En caso contrario, el proceso espera a que el hijo termine. Utiliza execvp() para ejecutar el programa externo en el hijo. Muestra un mensaje de error si el comando no se puede ejecutar
int check_process (pid_t pid)
check_process
pid_t start_monitor (void)
start_monitor
int stop_process (pid_t pid)
stop_process
void set_noncanonical_mode (void)
set_noncanonical_mode Configura la terminal en modo no canónico. Funcionalidad: Ajusta la configuración de la terminal para permitir la lectura de entradas de teclado de inmediato, sin necesidad de pulsar "Enter". Permite a programas interactivos capturar y responder a las entradas del usuario en tiempo real, lo cual es útil para aplicaciones de shell y de monitoreo que necesitan reaccionar de inmediato ante las acciones del usuario.
void reset_terminal_mode ()
reset_terminal_mode Restaura la configuración original de la terminal. Funcionalidad: Revierte cualquier cambio realizado en la configuración de la terminal (por ejemplo, si se cambió a modo no canónico). Es especialmente importante para restaurar la configuración al salir de una aplicación de modo terminal, evitando que la terminal quede en un estado de configuración inusual.
void handle_keypress (void)
handle_keypress Detecta y maneja las pulsaciones de teclas en la terminal. Funcionalidad: Captura las teclas presionadas por el usuario en modo no canónico, lo cual permite que las entradas se procesen de inmediato sin requerir que el usuario presione "Enter". Dependiendo de la tecla presionada, la función puede ejecutar comandos específicos como salir, pausar, o realizar otras acciones. Esta función es fundamental para aplicaciones interactivas en la terminal, como una shell o un menú de control.
void timeout_handler (int sig)
timeout_handler Maneja el evento de tiempo de espera o inactividad. Funcionalidad: Se activa cuando el programa ha alcanzado un tiempo de espera, lo cual puede ser el resultado de inactividad del usuario o de no recibir una respuesta esperada. Esta función podría realizar acciones como restaurar el sistema a un estado seguro, cerrar sesiones activas, o mostrar un mensaje de advertencia. Esta función suele asociarse con un temporizador de tipo watchdog que controla el estado de la aplicación.
void timer_handler (int sig)
timer_handler Función que maneja la señal generada por el temporizador. Funcionalidad: Este manejador (handler) se invoca cada vez que el temporizador emite una señal, generalmente SIGALRM. Puede realizar acciones como actualizar información, refrescar la pantalla o recopilar datos de uso del sistema. Al ser un manejador de señal, debe ser rápido y no bloquearse, ya que la señal podría interrumpir el flujo normal del programa.
void setup_timer (int period)
setup_timer Configura un temporizador que se activa periódicamente. Funcionalidad: El argumento period define el intervalo en milisegundos. Usualmente, configura una señal para que se envíe al proceso a intervalos regulares. Por ejemplo, puede utilizar timer_settime para establecer un temporizador que emite señales SIGALRM o SIGVTALRM. Este tipo de temporizador es útil en aplicaciones que requieren una acción repetitiva, como monitorear o refrescar datos.
int process_control_json (const char *json_string, int monitor_pid)
process_control_json Procesa un mensaje en formato JSON y ejecuta alguna acción en función del contenido del JSON, generalmente para controlar o comunicar información al proceso con ID monitor_pid.
char * read_json_file (const char *filename)
read_json_file
Variables
struct termios original_mode
Defi.
ProcessControl process = {0}
Defi.
Detailed Description
Implementación de funciones de herramientas y utilidades.
Este archivo contiene la implementación de funciones relacionadas con herramientas y utilidades generales del sistema, además de manejar variables globales como el estado del terminal.
Created by DARIO on 27/10/24.
Definition in file tools.c.
Function Documentation
check_process()
int check_process (pid_t pid)
check_process
Verifica si un proceso con el PID dado está activo.
Returns
asd Propósito: Verifica el estado de un proceso usando su PID. Funcionalidad: Evalúa si el proceso está corriendo, si terminó normalmente o si fue interrumpido por una señal, y retorna un código de estado.
Definition at line 92 of file tools.c.
handle_keypress()
void handle_keypress (void)
handle_keypress Detecta y maneja las pulsaciones de teclas en la terminal. Funcionalidad: Captura las teclas presionadas por el usuario en modo no canónico, lo cual permite que las entradas se procesen de inmediato sin requerir que el usuario presione "Enter". Dependiendo de la tecla presionada, la función puede ejecutar comandos específicos como salir, pausar, o realizar otras acciones. Esta función es fundamental para aplicaciones interactivas en la terminal, como una shell o un menú de control.
Detecta y maneja la pulsación de teclas en la terminal.
Definition at line 254 of file tools.c.
launchProg()
void launchProg (char ** args, int background)
launchProg punto 3 de tp2 Ejecuta un programa externo con los argumentos dados args[]: Array de cadenas que representa el comando y sus argumentos. background: Indica si el proceso debe ejecutarse en segundo plano. Funcionamiento: Crea un proceso hijo usando fork(). Si background es 1, el proceso se ejecuta en segundo plano. En caso contrario, el proceso espera a que el hijo termine. Utiliza execvp() para ejecutar el programa externo en el hijo. Muestra un mensaje de error si el comando no se puede ejecutar
Lanza un proceso con los argumentos proporcionados y permite la opción de ejecutarlo en segundo plano.
Definition at line 34 of file tools.c.
process_control_json()
int process_control_json (const char * json_string, int monitor_pid)
process_control_json Procesa un mensaje en formato JSON y ejecuta alguna acción en función del contenido del JSON, generalmente para controlar o comunicar información al proceso con ID monitor_pid.
Procesa un JSON para controlar el comportamiento del proceso basado en la configuración.
Funcionalidad: Recibe una cadena JSON y un identificador de proceso (monitor_pid). Parseará el JSON para extraer datos o comandos que se quieran enviar al proceso indicado. Esto puede incluir comandos de inicio, detención o cambio de estado de un proceso. Dependiendo del diseño, esta función puede trabajar junto con otras funciones de control de procesos para administrar y monitorear el proceso indicado.
Returns
da
Definition at line 389 of file tools.c.
References ProcessControl::is_running, ProcessControl::period, ProcessControl::pid, process, setup_timer(), and ProcessControl::timeout.
read_json_file()
char* read_json_file (const char * filename)
read_json_file
Lee un archivo JSON y devuelve su contenido como una cadena.
Returns
char asd Lee y aplica la configuración de un archivo JSON. Lee las configuraciones almacenadas en config.json, analiza el contenido JSON y lo aplica al proceso de monitoreo (pid).
Definition at line 456 of file tools.c.
reset_terminal_mode()
void reset_terminal_mode (void)
reset_terminal_mode Restaura la configuración original de la terminal. Funcionalidad: Revierte cualquier cambio realizado en la configuración de la terminal (por ejemplo, si se cambió a modo no canónico). Es especialmente importante para restaurar la configuración al salir de una aplicación de modo terminal, evitando que la terminal quede en un estado de configuración inusual.
Restablece el modo de la terminal a la configuración original (modo canónico).
Definition at line 238 of file tools.c.
References original_mode.
Referenced by set_noncanonical_mode().
set_noncanonical_mode()
void set_noncanonical_mode (void)
set_noncanonical_mode Configura la terminal en modo no canónico. Funcionalidad: Ajusta la configuración de la terminal para permitir la lectura de entradas de teclado de inmediato, sin necesidad de pulsar "Enter". Permite a programas interactivos capturar y responder a las entradas del usuario en tiempo real, lo cual es útil para aplicaciones de shell y de monitoreo que necesitan reaccionar de inmediato ante las acciones del usuario.
Configura la terminal en modo no canónico para capturar las teclas inmediatamente.
Definition at line 219 of file tools.c.
References original_mode, and reset_terminal_mode().
setup_timer()
void setup_timer (int period)
setup_timer Configura un temporizador que se activa periódicamente. Funcionalidad: El argumento period define el intervalo en milisegundos. Usualmente, configura una señal para que se envíe al proceso a intervalos regulares. Por ejemplo, puede utilizar timer_settime para establecer un temporizador que emite señales SIGALRM o SIGVTALRM. Este tipo de temporizador es útil en aplicaciones que requieren una acción repetitiva, como monitorear o refrescar datos.
Configura un temporizador con un intervalo determinado en segundos.
Definition at line 351 of file tools.c.
References process, and ProcessControl::timer_id.
Referenced by process_control_json().
start_monitor()
pid_t start_monitor (void)
start_monitor
Inicia el monitor en segundo plano y devuelve el PID del proceso monitor.
Returns
d Inicia un proceso de monitoreo del sistema. Lanza el proceso que monitorea el sistema y retorna su ID de proceso (PID).
Definition at line 128 of file tools.c.
References MAX_PATH, and METRIC_RELATIVE_PATH.
stop_process()
int stop_process (pid_t pid)
stop_process
Detiene un proceso monitor en ejecución.
Parameters
pid
Returns
inter Detiene el proceso de monitoreo del sistema. Envia una señal para terminar el proceso identificado por pid. Retorna 0 si el proceso se detuvo correctamente, y -1 si hubo un error.
Definition at line 183 of file tools.c.
timeout_handler()
void timeout_handler (int sig)
timeout_handler Maneja el evento de tiempo de espera o inactividad. Funcionalidad: Se activa cuando el programa ha alcanzado un tiempo de espera, lo cual puede ser el resultado de inactividad del usuario o de no recibir una respuesta esperada. Esta función podría realizar acciones como restaurar el sistema a un estado seguro, cerrar sesiones activas, o mostrar un mensaje de advertencia. Esta función suele asociarse con un temporizador de tipo watchdog que controla el estado de la aplicación.
Manejador de señal que se activa cuando el temporizador alcanza su límite.
Definition at line 305 of file tools.c.
References ProcessControl::pid, and process.
timer_handler()
void timer_handler (int sig)
timer_handler Función que maneja la señal generada por el temporizador. Funcionalidad: Este manejador (handler) se invoca cada vez que el temporizador emite una señal, generalmente SIGALRM. Puede realizar acciones como actualizar información, refrescar la pantalla o recopilar datos de uso del sistema. Al ser un manejador de señal, debe ser rápido y no bloquearse, ya que la señal podría interrumpir el flujo normal del programa.
Manejador de señales para eventos de temporizador.
Definition at line 325 of file tools.c.
References ProcessControl::is_running, ProcessControl::pid, and process.
Variable Documentation
original_mode
struct termios original_mode
Defi.
Definition at line 1 of file tools.c.
Referenced by reset_terminal_mode(), and set_noncanonical_mode().
process
ProcessControl process = {0}
Defi.
Definition at line 20 of file tools.c.
Referenced by process_control_json(), setup_timer(), timeout_handler(), and timer_handler().