My Project: include/tools.h File Reference
tools.h File Reference
Created by DARIO on 27/10/24. declaracones defuncones relacionadas con herramentas y utildades.
#include <cjson/cJSON.h>
#include <errno.h>
#include <fcntl.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <sys/utsname.h>
#include <sys/wait.h>
#include <termios.h>
#include <time.h>
#include <unistd.h>
Data Structures
struct ProcessControl
Estructura que representa la configuración de control de un proceso.
Macros
#define MAX_PATH 1024
Define la longitud máxima permitida para una ruta de archivo.
#define METRIC_RELATIVE_PATH "../../so-i-24-chp2-dariocastillo11/metrics"
D.
Functions
pid_t start_monitor ()
Inicia el monitor en segundo plano y devuelve el PID del proceso monitor.
int check_process (pid_t pid)
Verifica si un proceso con el PID dado está activo.
pid_t stop_process (pid_t pid)
Detiene un proceso monitor en ejecución.
void launchProg (char **args, int background)
Lanza un proceso con los argumentos proporcionados y permite la opción de ejecutarlo en segundo plano.
void cjson_manager (int doc)
Administra y maneja el contenido JSON utilizando la biblioteca cJSON.
void reset_terminal_mode (void)
Restablece el modo de la terminal a la configuración original (modo canónico).
void handle_keypress ()
Detecta y maneja la pulsación de teclas en la terminal.
void set_noncanonical_mode ()
Configura la terminal en modo no canónico para capturar las teclas inmediatamente.
void timer_handler (int sig)
Manejador de señales para eventos de temporizador.
void setup_timer (int period)
Configura un temporizador con un intervalo determinado en segundos.
int process_control_json (const char *json_string, int monitor_pid)
Procesa un JSON para controlar el comportamiento del proceso basado en la configuración.
void timeout_handler (int sig)
Manejador de señal que se activa cuando el temporizador alcanza su límite.
char * read_json_file (const char *filename)
Lee un archivo JSON y devuelve su contenido como una cadena.
Detailed Description
Created by DARIO on 27/10/24. declaracones defuncones relacionadas con herramentas y utildades.
Definition in file tools.h.
Macro Definition Documentation
MAX_PATH
#define MAX_PATH 1024
Define la longitud máxima permitida para una ruta de archivo.
Este macro se utiliza para definir el tamaño máximo de un buffer que contendrá una ruta de archivo completa.
Definition at line 31 of file tools.h.
METRIC_RELATIVE_PATH
#define METRIC_RELATIVE_PATH "../../so-i-24-chp2-dariocastillo11/metrics"
D.
Definition at line 37 of file tools.h.
Function Documentation
check_process()
int check_process (pid_t pid)
Verifica si un proceso con el PID dado está activo.
Parameters
pid dad
Returns
int 1 si el proceso está activo, 0 si no lo está.
Verifica si un proceso con el PID dado está activo.
Returns
asd Propósito: Verifica el estado de un proceso usando su PID. Funcionalidad: Evalúa si el proceso está corriendo, si terminó normalmente o si fue interrumpido por una señal, y retorna un código de estado.
Definition at line 97 of file tools.c.
cjson_manager()
void cjson_manager (int doc)
Administra y maneja el contenido JSON utilizando la biblioteca cJSON.
Parameters
doc Identificador o código del documento JSON a procesar.
handle_keypress()
void handle_keypress ()
Detecta y maneja la pulsación de teclas en la terminal.
Detecta y maneja la pulsación de teclas en la terminal.
Definition at line 273 of file tools.c.
launchProg()
void launchProg (char ** args, int background)
Lanza un proceso con los argumentos proporcionados y permite la opción de ejecutarlo en segundo plano.
Parameters
args Los argumentos del proceso a ejecutar.
background 1 para ejecutar el proceso en segundo plano, 0 para ejecutarlo en primer plano.
Lanza un proceso con los argumentos proporcionados y permite la opción de ejecutarlo en segundo plano.
Definition at line 35 of file tools.c.
process_control_json()
int process_control_json (const char * json_string, int monitor_pid)
Procesa un JSON para controlar el comportamiento del proceso basado en la configuración.
Parameters
json_string La cadena JSON que contiene los parámetros de control del proceso.
monitor_pid El ID del proceso a controlar.
Returns
int 1 si el procesamiento se realizó correctamente, 0 en caso de error.
Procesa un JSON para controlar el comportamiento del proceso basado en la configuración.
Funcionalidad: Recibe una cadena JSON y un identificador de proceso (monitor_pid). Parseará el JSON para extraer datos o comandos que se quieran enviar al proceso indicado. Esto puede incluir comandos de inicio, detención o cambio de estado de un proceso. Dependiendo del diseño, esta función puede trabajar junto con otras funciones de control de procesos para administrar y monitorear el proceso indicado.
Returns
da
Definition at line 395 of file tools.c.
References ProcessControl::is_running, ProcessControl::period, ProcessControl::pid, process, setup_timer(), and ProcessControl::timeout.
read_json_file()
char* read_json_file (const char * filename)
Lee un archivo JSON y devuelve su contenido como una cadena.
Parameters
filename El nombre del archivo JSON a leer.
Returns
char* Una cadena con el contenido del archivo JSON, o NULL en caso de error. La memoria para la cadena debe liberarse después de su uso.
Lee un archivo JSON y devuelve su contenido como una cadena.
Returns
char asd Lee y aplica la configuración de un archivo JSON. Lee las configuraciones almacenadas en config.json, analiza el contenido JSON y lo aplica al proceso de monitoreo (pid).
Definition at line 454 of file tools.c.
reset_terminal_mode()
void reset_terminal_mode (void)
Restablece el modo de la terminal a la configuración original (modo canónico).
Restablece el modo de la terminal a la configuración original (modo canónico).
Definition at line 255 of file tools.c.
References original_mode.
Referenced by set_noncanonical_mode().
set_noncanonical_mode()
void set_noncanonical_mode (void)
Configura la terminal en modo no canónico para capturar las teclas inmediatamente.
Configura la terminal en modo no canónico para capturar las teclas inmediatamente.
Definition at line 233 of file tools.c.
References original_mode, and reset_terminal_mode().
setup_timer()
void setup_timer (int period)
Configura un temporizador con un intervalo determinado en segundos.
Parameters
period El período de tiempo en segundos para el temporizador.
Configura un temporizador con un intervalo determinado en segundos.
Definition at line 354 of file tools.c.
References process, and ProcessControl::timer_id.
Referenced by process_control_json().
start_monitor()
pid_t start_monitor (void)
Inicia el monitor en segundo plano y devuelve el PID del proceso monitor.
Returns
pid_t El PID del proceso monitor, o -1 en caso de error.
Inicia el monitor en segundo plano y devuelve el PID del proceso monitor.
Returns
d Inicia un proceso de monitoreo del sistema. Lanza el proceso que monitorea el sistema y retorna su ID de proceso (PID).
Definition at line 136 of file tools.c.
References MAX_PATH, and METRIC_RELATIVE_PATH.
stop_process()
pid_t stop_process (pid_t pid)
Detiene un proceso monitor en ejecución.
Returns
pid_t El PID del proceso detenido, o -1 en caso de error.
Detiene un proceso monitor en ejecución.
Parameters
pid
Returns
inter Detiene el proceso de monitoreo del sistema. Envia una señal para terminar el proceso identificado por pid. Retorna 0 si el proceso se detuvo correctamente, y -1 si hubo un error.
Definition at line 193 of file tools.c.
timeout_handler()
void timeout_handler (int sig)
Manejador de señal que se activa cuando el temporizador alcanza su límite.
Parameters
sig Manejador de señal que se activa cuando el temporizador alcanza su límite.
Definition at line 310 of file tools.c.
References ProcessControl::pid, and process.
timer_handler()
void timer_handler (int sig)
Manejador de señales para eventos de temporizador.
Parameters
sig
Manejador de señales para eventos de temporizador.
Definition at line 330 of file tools.c.
References ProcessControl::is_running, ProcessControl::pid, and process.